### ISSUE TITLE
GipFace's list of requirements (Extended)

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#150]
#### PRIORITY
- [ ] Centralized chatroom (the community is the only thing that would give an AW client life)
  Matchmaker
- [x] See enemy turn in progress (Custom Wars didn't have this!)
- [ ] In-game clock (static from 1-5 minutes or based on turns/unit count -- I like :20 + :03/unit)
- [ ] Spectating
- [ ] Toggle AW2/AW3/AW4 mode
- [x] Maintain relevant quirky gameplay accuracy in the canon games (50 unit limit, AW4 defensive zone charging, terrain def. reduces luck, APC/rig supply after upkeep, etc.)
- [ ] Rejoin on disconnect options
- [ ] Two words that would be revolutionary: game replays. Game replays should have the map embedded in it so that anyone can view the replay file, plus maybe a hash tag to prevent tampering.
- [ ] As a bonus, players should be able to export maps from replays if they like it.
#### HIGH
- [ ] Spectate host. A tournament organizer could host the game and let two people play.
- [ ] Spectate camera (for fog mode - have a no-fog camera and specific player cameras)
- [x] Unit and map animation
- [ ] Music and sound effects
- [x] Completely remappable input
- [ ] Random player position (players don't know if they're P1 or P2 until the game starts!)
- [ ] All menu items available as buttoned commands
#### MEDIUM
- [ ] "Metal Gear ! warning" This was in that Strategery flash game. When advancing a unit, any enemy units that may attack it the following turn will have a ! pop up. I really liked this.
- [ ] 2-click command mode, user selectable. This would be really cool. Left-click on a unit to select, and then movement will follow the pointer. Hovering over an enemy will show projected damage, and left-clicking on it would execute a command. Moving to an empty space is an automatic wait/supply/capture command, except only when unloading or constructing is available (which requires >2 clicks). If blitz play were to be implemented, this would speed things up a lot. But perhaps some people would like the old AW3 or AW4 command mode, and that's fine too. Right-click, of course, is cancel.
- [ ] "Attach CO to this unit" command, which would be needed in 2-click command mode
- [ ] Toggle CO blind pick or 1P selects CO first
#### LOW
- [ ] New art for canon COs
- [ ] Map design mirror fill. Make one half of the map and tell the map editor to mirror it for perfect symmetry! No more messing up.
- [ ] Exact health mode. Shows exact health instead of /10 HP
- [ ] Exact projected counterattack damage mode. Show multiple possibilities based on luck outcome. (If projected damage is 55%, show 4HP and 5HP counterattack damage)
- [ ] Set low ammo/gas warning levels. It's set at 50% or below by default; making it customizable would be cute.
- [ ] Auto end turn if you cannot build anything or issue a command, and you cannot activate a COP
- [ ] Force animation off or minimum animation if clock is under 20 seconds
- [x] Custom units
- [x] Custom COs

**Comment by ctomni231** [comment]
Extended the list of Gipface's Requirements to match the new list recently put up. More information about my thoughts on the list can be found by visiting the blog topic...

http://cwtactics.blogspot.de/2015/08/off-grid-what-we-need-part-ii.html

**Comment by Tapsi** [comment]
@ctomni231 we should remove this one by splitting the tasks into single stories. IMHO every point should be a story.

**Comment by ctomni231** [comment]
Yeah, I agree. I still want to find a way to tag this back to the original issue. I want to take some time to go and do this, maybe leaving it in the Dev- Backlog and just making new tickets would be good enough for the future. Either way, I would probably hold off on splitting this until after 0.36 completion.
