### ISSUE TITLE
Enhance Use-Cases of the storage system

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#223]
At the moment we're using lawnchair simply for webSQL and indexed-DB. In future we wan't to use also HTML5-File-API when it's available on the client ( for music ). 

**Use-Case:**

    IF client has file-API and object is music THEN store( file_API, obj )
    ELSE
      IF client has indexed-db THEN store( file_API, obj )
      IF client has webSQL THEN store( file_API, obj )

At all we need also an idea about the storage limits of chrome. In this case it's interesting how much storage we allowed to have and when it's getting deleted by chrome.

The current plan is not to use chrome-packaged-app for now.

**Comment by ctomni231** [comment]
Done
