### ISSUE TITLE
Create more detailed README's

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#254]
## Description

In order to start making Custom Wars Tactics more friendly for new people wanting to edit the code. A series of readme's will be written to show modification users and programmers which files are of interest within the Custom Wars Tactics code base. These changes will first only apply to the /src folder of the repository. As time moves forward, it might move on to the other parts. Below is an example of what the Readme's will mimic.

https://github.com/aurapm/aura
## Requirements
- ReadMe contains system requirements
- ReadMe contains deployment instructions
- ReadMe contains game manual

**Comment by Tapsi** [comment]
@ctomni231 Has now the status "ready" and is included into 0.36 milestone.
