### ISSUE TITLE
WebGL Performance update

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#323]
For the desktop version of the Web Client, we will add WebGL to speed up the images drawn on the desktop devices.

**Canvas** vs **WebGL** performance gain 2D 

* chrome 350%
* firefox 250%

**Comment by Tapsi** [comment]
Still not ready at the moment. Furthermore this ticket should be in the backlog as long 0.36 isn't released.

@ctomni231 may this ticket is obselete ?

**Comment by ctomni231** [comment]
Ummm... Let's push this ticket to the Backlog until further notice and we are able to chat about it some more. (Which is already done... funnily).

**Comment by ctomni231** [comment]
I do not think WebGL will have to be considered anymore. The benchmark tests of the JSlix graphics engine resulted in speeds that are more than satisfactory for PC users. Also, support for WebGL is still weak in Internet Explorer. Given these two aspects, I am closing this ticket so we keep the amount of overarching paths low.

This issue may be re-opened if there are any objections.
