### ISSUE TITLE
AW Look & Feel - Bad damage formula

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#335]
**Describe the problem:** Andy recon (100A) attacks 100D 10HP artillery on city. Recon vs. artillery BD Is 45. City adds 30D.
**Describe the expected result:** Damage should be between 45 x .7 = 31 (0 luck) and 54 x .7 = 37 (9 luck). 41 health was removed from the unit.

![image](https://f.cloud.github.com/assets/1644926/1797105/6803f3a6-6aaa-11e3-8e6b-389543c9b7c8.png)

**By:** Gipface

---

Related to Issue #334. 

I'm going to specifically look up the exact damage formula to see if the one we are using is the correct damage formula for AWDS. Currently this is under review, but I'll double check with the original poster to make sure everything checks out.

**Comment by MasterKnightDH** [comment]
AWDS uses the same formula as AW2.

I also need to point out that luck damage is handled after the attack power but before the defense power and HP in all games.

**Comment by ctomni231** [comment]
Thanks for the information. Do you happen to have the exact formula for the games? So far, we have been using WWN as the source of the formula. It would be good to have a secondary source. Thanks a billion.

**Comment by MasterKnightDH** [comment]
If you have a RAM search emulator and a clean AW2 ROM, you can find the listed damage at address 30013E4, and at 30013E0 is the address that holds the base damage multiplied by the attacking CO's damage multiplier. I can be sure that 30013E0 is used in the actual combat, has luck damage added to it, and then the rest is taken care of.
