### ISSUE TITLE
Internet Explorer 10 -  AppCache Fatal Error

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#361]
# Description

It seems to me that the data just fails to be cached in the offline storage. It is strange because I don't remember IE having problems with this past IE9, but I will look into it. If anything, this webpage should shed some light into the situation since it was created specifically for IE 10.

![image](https://f.cloud.github.com/assets/1644926/2190424/1bc2e5fe-9829-11e3-90dd-de8cf6e48bd0.png)

http://blogs.msdn.com/b/ie/archive/2011/09/27/building-offline-experiences-with-html5-appcache-and-indexeddb.aspx

# Steps to reproduce

 _(only for bug issues)_

1. Open the web page in IE10

### Expected outcome

Game starts

### Actual outcome

Game crashes with an error message on the console

### Affected environments 

System Parameter | Value
---------------------- | ----------------------
**Game Version** | 0.3.5
**Operating Device** | PC
**Operating System** | Windows 7
**Browser & Browser Version** | Inernet Explorer 10
**Problem Urgency** | 10

# Links to other issues

- requires #379 

# Tasks

- [ ] Analyse problem
- [ ] Define a solution

**Comment by Tapsi** [comment]
will be fixed by #421
