### ISSUE TITLE
Artillery takes counterattack damage?

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#365]
# Description

![image](https://cloud.githubusercontent.com/assets/1644926/2751344/bcd37ec2-c8c6-11e3-96b7-86b3e83accc4.png)

This issue is confirmed. Artillery and other indirects take damage when they attack direct units. The correct outcome is that they aren't supposed to take counterattack damage. I guess this one was overlooked.

# Steps to reproduce

 _(only for bug issues)_

1. Build artillery
2. Move near an enemy unit with direct combat mode
3. Attack that unit

### Expected outcome

Artillery takes no counter damage

### Actual outcome

Artillery takes counter damage

### Affected environments 

Every system

# Links to other issues

- requires #379

# Tasks

- [ ] Fix it

**Comment by Tapsi** [comment]
will be fixed by #421
