### ISSUE TITLE
Finish Button Design

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#386]
# Description

Should be like the last design. The base class `UiField` contains the base rendering.

![image](https://cloud.githubusercontent.com/assets/1644926/6310776/ffcdd216-b90e-11e4-8fdd-76958de57ea5.png)
- Edges == Four Corner Images
- Graphs == Side Image
- area == Background Area
# Tasks
- [ ] Finish button design as images
  - [ ] edges (4)
  - [ ] graphs 
  - [ ] area

**Comment by Tapsi** [comment]
@ctomni231 : "Still in progress to find a good new design."
