### ISSUE TITLE
Create an update manager

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#419]
## Description

The past showed a lot of "remove your cache" requirements after updates are released. It's quite okay that this happens often during an alpha phase, but its not user friendly. We should try to build an algorithm which gives us the ability to do persistent storage manipulation automatically without having the needs to do this manually when the game updates.

## Requirements

- [x] The game version will be persisted in the persistent storage

- [x] The developer can create update classes which does stuff when updating to a given version

- [x] The new version will be persisted after the update process is done  

- [x] The system works with ordered update steps  

        E.g. when updating from version 1 to 4 
         1. the update classes for version 2 will be executed 
         2. the update classes for version 3 will be executed 
         3. the update classes for version 4 will be executed 

- [x] If the update fails then the user gets an error dialog with the option to clean the persistent storage

**Comment by Tapsi** [comment]
@ctomni231 is that okay ?

**Comment by ctomni231** [comment]
Perfectly fine. Ship it.
