### ISSUE TITLE
Implement error management

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#422]
## Description

There are several places at the moment where errors aren't catched. The best example are null / undefined access everywhere. We should follow the _optional_ design pattern to minimize the existence of them plus should move every error to a central error manager.

#### Nullable pattern

      Optional.of(value) 
        - get(): T
        - getOrElse(defValue): T 
        - getOrThrow(error): T
        - isPresent(): boolean
        - ifPresent(cb): void
        - ifOrElsePresent(thenCb, elseCb): void 

      Optional.of(null).get() // error
      Optional.of(1).get().get() // 1
      Optional.of(null).getOrElse(2) // 2
      Optional.of(null).getOrThrow("Wuff") // Error("Wuff")
      Optional.of({}).isPresent() // true
     

## Requirements

- [ ] Methods only using ```null``` as value when the return content is optional
- [ ] If a method has an optional return then Optional.of(...) will be used
- [ ] If a method has no optional return and finds an error then an error will be thrown or a non null value will be returned
- [ ] Nullable (static version of Optional.of(...)) will be removed
- [x] There is an error manager which is injectable 
- [ ] Known error situations will be catched (like during data loading) and send to the error manager

**Comment by ctomni231** [comment]
Agreed this should be implemented
