### ISSUE TITLE
CWTCore: Game Startup - Loading State

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#431]
## State Explanation

This is going to be the first screen the users see when they access the game. Therefore, it is a good place for users to experiment with the controls. Functionality within this space should be as simplified as possible.
## Acceptance Criteria
- [ ] Game logo displayed
- [ ] Displays the title of the game
- [ ] Loads all necessary assets into the system when enter state
  - [x] game data files
    - [x] The weather data will be grabbed from the game data directory
    - [x] The unit data will be grabbed from the game data directory
    - [x] The property data will be grabbed from the game data directory
    - [x] The tile data will be grabbed from the game data directory
  - [ ] game image files
  - [ ] game audio files
- [ ] "Press Start" text somewhere visible after the assets loaded completely
## Optional
- [ ] Displays tip and tricks of the game
## Button Functionality
- [x] **Ok:** Proceed to _**Main Menu State (#433)**_ when "Press Start" is visble else no function
- [ ] **Cancel:** No function
## State Helpers

Modules Required:
- [ ] JSlix Graphics Engine (#435)
- [ ] NekoScript Logic Engine

Optional:
- [ ] Music Engine

**Comment by Tapsi** [comment]
Tips are loaded in the current build, but only visible on the developer console.
