### ISSUE TITLE
CWTCore: State Helper - JSlix Graphics Engine

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#435]
## Helper Explanation

The JSlix Graphics Engine is the name behind the engine that will be drawing the graphics for the game. The key function of the graphics engine is to display items to the screen, but an extra focus will be put on the system working flawlessly in as many browsers as possible, as long as they support the canvas.

This system is fully image based, and focuses on the manipulation of images to draw onto the canvas. Therefore keeping the engine at a very high frame rate with limited memory usage.Testing is taking place on a variety of architectures and devices to ensure robustness. These will be listed here once the engine is included into the main game located in src_new.
## Functionality

Tasks will only be marked as completed upon their inclusion into src_new.
- [x] addImage: Adds an image and stores it into the system
- [x] getImage: Gets an image for drawing
- [x] recolorImage: Recolors an image according to matching pixels
- [x] blendImage: Shades an image with an overlaying color of your choice
- [x] flipX: Flips an image alongside the x-axis
- [x] flipY: Flips an image alongside the y-axis
- [x] rotate90: Rotates an image 90 degrees clockwise
- [x] pixelmoveX: Moves a column of pixels in the X direction a certain distance
- [x] pixelmoveY: Moves a row of pixels in the Y direction a certain distance 
- [x] cutImage (Deprecated): Cuts an image by a certain length and width before drawing

**Comment by Tapsi** [comment]
@ctomni231 whats the benefit to include a deprecated API (cutImage) ?

**Comment by ctomni231** [comment]
This is a full API pulled over from JSlix in Java. cutImage() was included on the ticket because it was part of the old API. 

This section is under continued construction, and the item functionality will change. cutImage() will very likely be scrapped as JavaScript has this functionality. 

Thanks for calling this to attention.

**Comment by ctomni231** [comment]
This was completed as of commit acc9893.
