### ISSUE TITLE
CWTCore: Multicore mode

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#437]
## Description

We need to make sure that the graphic stack is able to render at 60 fps (or at least without heavy fps drops). To achieve this we should separate the game logic into a separate thread which not slows down the GUI thread if heavier game operations happens.

## Acceptance criteria

- [x] The game uses multiple cores if available to run more efficiently on modern CPUs

## Documentation

- The game uses the WebWorker API to achieve the multi core support
- To build the game with dual-core support you need to add ```-dualcore``` to the build parameters
- Game and client (GUI) only communicates with the event bridge
  - **Client -> Game:** ```client_event_xyz```
  - **Game -> Client:** ```game_event_xyz```

## Afflicted commits

- [duale core mode](https://github.com/ctomni231/cwtactics/commit/c4a8b4f074286a7abb90fbe3208bc0d607076939)
- [rewritten build file](https://github.com/ctomni231/cwtactics/commit/1c919505320a19134704ecca2deccce4037d303c)

**Comment by ctomni231** [comment]
I don't know if we can guarantee this on all system architectures, so at the very least this shouldn't be the default setting.

Currently, we do all our heaviest loading at the start of the game. The only other place where it may get heavy is with map loading. It is acceptable to wait a little in those areas. 

I would say this is acceptable as long as we do not have to redo large portions of the program to accomplish it.

**Comment by Tapsi** [comment]
@ctomni231 

The WebWorker API is supported on every browser we support ([canIUse - WebWorkers](http://caniuse.com/#feat=webworkers)). Furthermore this feature uses a normal thread model which means it runs on one core as well on two cores. The difference would be ability of the dualcore cpu to run  the ui and the game code simultaneous.

At least the game builder can create a normal game file without web workers (aka the old game file before the commits above).
