### ISSUE TITLE
User Control - Keyboard Input

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#454]
This smaller ticket was spawned from the major ticket #453.

We should have various ways of providing input for the user. This ticket describes the keyboard section of the ticket. Optional commands do not need to be completed for this ticket to be closed:

  - [x] Up (key - up)
  - [x] Down (key - down)
  - [x] Left (key - left)
  - [x] Right (key - right)
  - [x] Select (key - space)
  - [x] Cancel (key - shift)

**Comment by Tapsi** [comment]
Removed zooming keys , because we do not need it right now. This can be added with another ticket when we need it.

**Comment by ctomni231** [comment]
Yeah, a totally agree with that. Closing for completion purposes.
