### ISSUE TITLE
[Question] Legal and license questions

### ISSUE THREAD

**Issue by tairosonloa** [ctomni231/cwtactics#498]
I see this project is under MPL-2.0 License. I would like to modify part of this and use it in a commercial project, of course meeting the license requirements. However, the [cwt_tileset](https://github.com/ctomni231/cwtactics/tree/master/image/cwt_tileset) looks like the original Nintendo copyrighted tile set. Also, I can't find a Nintendo reference in the _Legals_ section from the project official website: https://ctomni231.github.io/cwtactics/

Is this in fact available with a commercial use?

**Comment by ctomni231** [comment]
The Custom Wars Tactics main page has been updated

**Comment by ctomni231** [comment]
Fixed
